# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modifyWindow(object):
    def setupUi(self, modifyWindow):
        modifyWindow.setObjectName("modifyWindow")
        modifyWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        modifyWindow.resize(229, 200)
        modifyWindow.setMinimumSize(QtCore.QSize(229, 200))
        modifyWindow.setMaximumSize(QtCore.QSize(229, 200))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(modifyWindow)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(modifyWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.seed_Input = QtWidgets.QSpinBox(modifyWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seed_Input.sizePolicy().hasHeightForWidth())
        self.seed_Input.setSizePolicy(sizePolicy)
        self.seed_Input.setMinimumSize(QtCore.QSize(150, 0))
        self.seed_Input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seed_Input.setMaximum(2147483647)
        self.seed_Input.setDisplayIntegerBase(16)
        self.seed_Input.setObjectName("seed_Input")
        self.horizontalLayout.addWidget(self.seed_Input)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.findGame_btn = QtWidgets.QPushButton(modifyWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findGame_btn.sizePolicy().hasHeightForWidth())
        self.findGame_btn.setSizePolicy(sizePolicy)
        self.findGame_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.findGame_btn.setObjectName("findGame_btn")
        self.verticalLayout.addWidget(self.findGame_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.getSeed_btn = QtWidgets.QPushButton(modifyWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getSeed_btn.sizePolicy().hasHeightForWidth())
        self.getSeed_btn.setSizePolicy(sizePolicy)
        self.getSeed_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.getSeed_btn.setObjectName("getSeed_btn")
        self.verticalLayout.addWidget(self.getSeed_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.modifySeed_btn = QtWidgets.QPushButton(modifyWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifySeed_btn.sizePolicy().hasHeightForWidth())
        self.modifySeed_btn.setSizePolicy(sizePolicy)
        self.modifySeed_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.modifySeed_btn.setObjectName("modifySeed_btn")
        self.verticalLayout.addWidget(self.modifySeed_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(modifyWindow)
        QtCore.QMetaObject.connectSlotsByName(modifyWindow)

    def retranslateUi(self, modifyWindow):
        _translate = QtCore.QCoreApplication.translate
        modifyWindow.setWindowTitle(_translate("modifyWindow", "修改种子"))
        self.label.setText(_translate("modifyWindow", "种子："))
        self.findGame_btn.setText(_translate("modifyWindow", "查找游戏"))
        self.getSeed_btn.setText(_translate("modifyWindow", "获取当前种子"))
        self.modifySeed_btn.setText(_translate("modifyWindow", "修改种子"))
